USE ASSIGNMENT;
CREATE TABLE Students (
Student_ID INT,
Name VARCHAR(50),
Course VARCHAR(50),
Marks INT,
Age INT,
City VARCHAR(50),
Scholarship INT
);

INSERT INTO Students VALUES
(1,'Ravi','Math',85,20,'Chennai',NULL),
(2,'Priya','Science',92,21,'Delhi',10000),
(3,'Amit','English',75,19,'Mumbai',5000),
(4,'Sneha','Math',88,22,'Kolkata',NULL),
(5,'John','History',67,20,'Chennai',NULL),
(6,'Meena','Science',95,23,'Delhi',15000),
(7,'Karan','English',70,20,'Bangalore',3000),
(8,'Divya','History',80,22,'Mumbai',NULL);
SELECT NAME,MARKS FROM STUDENTS WHERE MARKS BETWEEN 70 AND 80;
SELECT NAME,AGE FROM STUDENTS WHERE AGE BETWEEN 20 AND 22;
SELECT NAME FROM STUDENTS WHERE NAME LIKE('P%');
SELECT NAME,CITY FROM STUDENTS WHERE CITY LIKE('%AI%');
SELECT NAME FROM STUDENTS WHERE NAME LIKE("_R%");
SELECT NAME,MARKS FROM STUDENTS ORDER BY MARKS DESC LIMIT 3;
SELECT NAME,SCHOLARSHIP FROM STUDENTS WHERE SCHOLARSHIP IS NOT NULL;
SELECT NAME,CITY FROM STUDENTS WHERE (SELECT COUNT(CITY='Delhi') FROM STUDENTS where city='delhi' GROUP BY CITY )>1 and city='delhi';
SELECT NAME,COURSE,AGE FROM STUDENTS WHERE COURSE='MATH'AND AGE>21;
SELECT NAME,COURSE FROM STUDENTS WHERE COURSE IN('SCIENCE','ENGLISH');
SELECT NAME,CITY FROM STUDENTS WHERE CITY!='MUMBAI';
SELECT NAME,SCHOLARSHIP FROM STUDENTS WHERE SCHOLARSHIP IS NULL;
UPDATE STUDENTS SET SCHOLARSHIP=IFNULL(SCHOLARSHIP,0);
SELECT * FROM STUDENTS;
UPDATE STUDENTS SET SCHOLARSHIP=NULL WHERE SCHOLARSHIP=0;

UPDATE STUDENTS SET SCHOLARSHIP=COALESCE(SCHOLARSHIP,0);


