USE ASSIGNMENT;
CREATE TABLE Students10 (
Student_ID INT,
Name VARCHAR(50),
Course VARCHAR(50),
Marks INT,
Age INT,
City VARCHAR(50),
Scholarship INT
);

INSERT INTO Students10 VALUES
(1,'Ravi','Math',85,20,'Chennai',NULL),
(2,'Priya','Science',92,21,'Delhi',10000),
(3,'Amit','English',75,19,'Mumbai',5000),
(4,'Sneha','Math',88,22,'Kolkata',NULL),
(5,'John','History',67,20,'Chennai',NULL),
(6,'Meena','Science',95,23,'Delhi',15000),
(7,'Karan','English',70,20,'Bangalore',3000),
(8,'Divya','History',80,22,'Mumbai',NULL);
SELECT NAME,MARKS FROM STUDENTS10 WHERE MARKS BETWEEN 70 AND 80;
SELECT NAME,AGE FROM STUDENTS10 WHERE AGE BETWEEN 20 AND 22;
SELECT NAME FROM STUDENTS10 WHERE NAME LIKE('P%');
SELECT NAME,CITY FROM STUDENTS10 WHERE CITY LIKE('%AI%');
SELECT NAME FROM STUDENTS10 WHERE NAME LIKE("_R%");
SELECT NAME,MARKS FROM STUDENTS10 ORDER BY MARKS DESC LIMIT 3;
SELECT NAME,SCHOLARSHIP FROM STUDENTS10 WHERE SCHOLARSHIP IS NOT NULL;
SELECT NAME,CITY FROM STUDENTS10 WHERE (SELECT COUNT(CITY='Delhi') FROM STUDENTS10 where city='delhi' GROUP BY CITY )>1 and city='delhi';
SELECT NAME,COURSE,AGE FROM STUDENTS10 WHERE COURSE='MATH'AND AGE>21;
SELECT NAME,COURSE FROM STUDENTS10 WHERE COURSE IN('SCIENCE','ENGLISH');
SELECT NAME,CITY FROM STUDENTS10 WHERE CITY!='MUMBAI';
SELECT NAME,SCHOLARSHIP FROM STUDENTS10 WHERE SCHOLARSHIP IS NULL;
UPDATE STUDENTS10 SET SCHOLARSHIP=IFNULL(SCHOLARSHIP,0);
SELECT * FROM STUDENTS10;
UPDATE STUDENTS10 SET SCHOLARSHIP=NULL WHERE SCHOLARSHIP=0;
UPDATE STUDENTS10 SET SCHOLARSHIP=COALESCE(SCHOLARSHIP,0);